# Generated by Django 4.2.2 on 2023-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('m', 'm'), ('f', 'f')], default='м', max_length=1),
        ),
    ]
